
---
title: "Exploring the brain imaging metrics in association with GA at birth and at scan"
author: 
  - "Kadi Vaher"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=F, message=F}

library(tidyverse) 
library(here) 
library(RColorBrewer)
library(knitr)
library(ggpubr)
library(vegan)
library(ggrepel)
library(ape)
library(Hmisc)
library(corrplot)
library(car)
library(lmtest)

# set paths
knitr::opts_knit$set(root.dir=".", aliases=c(h = "fig.height", w = "fig.width", ow = "out.width"))
knitr::opts_chunk$set(dev = c('png'), 
                      fig.path = here("results", "figures", "explore_braindata", ""), dpi = 300)
theme_set(theme_light()) # global option for ggplot2

```

# Run the whole document - ONLY AT THE END OF THE WORKSTREAM

```{r knit, echo=F, eval=FALSE}
rmarkdown::render(input = here("scripts", "explore_braindata.Rmd"), output_dir = here("results", "reports"))
```

# Load and organise data

```{r organisedata_studygroup}

# read in data
tissue_morph <- read.csv(here("imaging_data", "processed_data", "tissues_cortex_morphology_diffusion_TEBC_17102022.csv"))
gfactors <- read.csv(here("imaging_data", "processed_data", "singlemetric_gfactors_matchingsample.csv"))

demo_matching <- read.csv(here("processed_data", "demographics_microbiome_mri_79_10102022.csv"))
demo_final_samples <- read.csv(here("processed_data", "demographics_clusterinfo_finalsamples_04102022.csv"))

pcoa <- read.csv(here("processed_data", "matchingsample_pcoa_relativeabundances.csv"))


#organise data
#select alpha diversity metrics
alpha <- demo_final_samples %>% select(sample_work_nr, Observed_rarefied, Shannon_rarefied)

#rename a column
pcoa <- pcoa %>% rename(sample_work_nr = X)

#merge all microbiota data
all_microbiota_matching <- merge(alpha, pcoa, by="sample_work_nr", all.y=T)

#subset the tissue morph file to only include the infants with matching microbiota
tissue_morph <- tissue_morph %>% subset(record_id %in% demo_matching$record_id)

gfactors <- gfactors %>% select(-GA_birth, -GA_mri, -sex)

#merge all brain data
all_brain_matching <- merge(tissue_morph, gfactors, by="record_id", all=T)

#select the columns that I will be using in analyses
#volumes: raw and relative
#microstucture: FA, MD and WM or GM optimised NDI, ODI and ISO -> still want to keep NDI and ODI as more specific measures of microstructure; I think especially important for the cortex to reflect cellular density and neurite geometrical complexity
all_brain_matching <- all_brain_matching %>% select(-WM_FA, -WM_MD, -WM_L1, -WM_RD, -WM_NDI_WM, -WM_ODI_WM, -WM_ISO_WM,
                                                    -CB_NDI_WM, -CB_ODI_WM, -CB_ISO_WM, -gAD,
                                                    -contains("MD"), -contains("L1"))

#select important demographics info
imp_demo <- demo_matching %>% select(record_id, sample_id, sample_work_nr, Time_point, Visit_number, GA_birth, extremely_preterm, postnatal_age_at_sample_d, PMA_sample_w, sex, GA_mri, birthweight_z_score, sepsis_binary, nec_binary, Vaginal_delivery, AB_after72h, BM_75)

all_data <- merge(imp_demo, all_brain_matching, by="record_id")

all_data <- merge(all_data, all_microbiota_matching, by="sample_work_nr")


```

# Statistics
Now do stats looking at the effect of GA at birth and GA at scan

```{r stats, ow="50%"}

#writing results into a table
results_table_studygroup2 <- data.frame(matrix(ncol = 7, nrow = 0))
x <- c("MRI_feature", "GAbirth_beta", "GAbirth_se","GAbirth_pval", "GAmri_beta", "GAmri_se","GAmri_pval")
colnames(results_table_studygroup2) <- x

for (i in 18:52) {
  metric <- (names(all_data[i]))
  print(metric)
  fit <- lm(scale(all_data[[i]]) ~ scale(GA_birth) + scale(GA_mri), data = all_data)
  print(summary(fit))
  
  #test if model residuals normally distributed
  print(shapiro.test(fit[['residuals']]))
  print(bptest(fit))
  #qqPlot(fit$residuals)
  par(mfrow = c(2, 2))
  plot(fit)
  
  #write into table
  tmp <- data.frame(matrix(ncol = 7, nrow = 1))
  y <- c("MRI_feature", "GAbirth_beta", "GAbirth_se","GAbirth_pval", "GAmri_beta", "GAmri_se","GAmri_pval")
  colnames(tmp) <- y
  tmp$MRI_feature <- names(all_data[i])
  tmp$GAbirth_beta <- fit$coefficients[2]
  tmp$GAmri_beta <- fit$coefficients[3]
  tmp$GAbirth_pval <- summary(fit)$coefficients[2,4]
  tmp$GAmri_pval <- summary(fit)$coefficients[3,4]
  tmp$GAbirth_se <- summary(fit)$coefficients[2,2]
  tmp$GAmri_se <- summary(fit)$coefficients[3,2]
  
  results_table_studygroup2 <- rbind(results_table_studygroup2, tmp)
}

kable(results_table_studygroup2)

write.csv(results_table_studygroup2, here("results", "tables", "MRIfeatures_GAbirth_GAscan_microbiotastudygroup.csv"), row.names=F)

```